package blatt20.aufgabe06;

public enum Gewichtsklasse {
    FLIEGENGEWICHT,
    BANTAMGEWICHT,
    FEDERGEWICHT,
    LEICHTGEWICHT,
    WELTERGEWICHT,
    MITTELGEWICHT,
    HALBSCHWERGEWICHT,
    SCHWERGEWICHT,
    SUPERSCHWERGEWICHT;
}
